image: docker:latest

services:
  - docker:dind

predict:
  variables:
    KAGGLE_USER_NAME: "$KAGGLE_USER_NAME"
    KAGGLE_KEY: "$KAGGLE_KEY"
  script:
    - docker build -t predict_interior_styles --build-arg KAGGLE_USER_NAME=$KAGGLE_USER_NAME --build-arg KAGGLE_KEY=$KAGGLE_KEY -f predict_interior_styles.dockerfile .
    - docker run predict_interior_styles
