image: docker:latest

services:
  - docker:dind

model:
  variables:
    SPACE_ACCESS_KEY: "$SPACE_ACCESS_KEY"
    SPACE_BUCKET_NAME: "SPACE_BUCKET_NAME"
    SPACE_SECRET_ACCESS_KEY: "$SPACE_SECRET_ACCESS_KEY"
    SPACE_URL: "$SPACE_URL"
  script:
    - docker build -t jobs .
    - docker run jobs
  artifacts:
    paths:
      - data
    expire_in: 24 hours
