qa-mixpanel:events-snapshot:on-schedule:
  only:
    refs:
      - schedules
    variables:
      - $WHICH_SCHEDULE == "qa-mixpanel-events-snapshot"

  environment:
    name: "qa"

  script:
    - ./mixpaneL_snapshot_events.sh