image: docker:latest

services:
  - docker:dind

predict:interior-styles:on-schedule:
  only:
    - schedules
  script:
    - docker build -t predict_interior_styles --build-arg KAGGLE_USER_NAME=$KAGGLE_USER_NAME --build-arg KAGGLE_KEY=$KAGGLE_KEY -f predict_interior_styles.dockerfile .
    - docker run -e MONGO_URL=$MONGO_URL predict_interior_styles